### ISSUE TITLE
Files in data folder are typically .rda 

### ISSUE THREAD

**Issue by jasonserviss** [nathanaelandrews/sp.scRNAseqAnalysis#1]
Better to save files in the data folder as an R data object, i.e. .rda, instead of .csv. This can be done several ways, see `help('save')` or `library(devtools); help('use_data')`. Further information about types of package data can be found at: [R packages: data](http://r-pkgs.had.co.nz/data.html).

**Comment by nathanaelandrews** [comment]
a8bf22f125b18b459ed2c4c9d6ea1f5f84f785be
