### ISSUE TITLE
another local path (source) in analysis file

### ISSUE THREAD

**Issue by jasonserviss** [nathanaelandrews/sp.scRNAseqAnalysis#5]
Technically, another local path in your analysis file (Cluster_By_Cell_Type.Rmd) is:

`source("RNAseq_functs.R")`

again, making the analysis only reproducible on your computer.

To avoid this you have 2 options:

1. (In my opinion the better option) You make a separate R package that has the functions included in the RNAseq_functs.R file. Luckily, I already did this for you [here](https://github.com/martinenge/RNAseqFunctions). To use these functions in the analysis file you need to install the package with the RNAseq functions on your computer and then write `library(RNAseqFunctions)` at the beginning of the analysis file. In addition you should probably list the RNAseqFunctions package in the Suggests: field of the DESCRIPTION file, see more on this [here](http://r-pkgs.had.co.nz/description.html#dependencies).

2. You include the functions in your package. This would mean you move the RNAseq_functs.R file into the R folder of your package. This will allow your package to be "self-contained" and your scripts to be reproducible BUT in the future if you have another package (i.e. somethingElseAnalysis) that uses these functions you will ALSO need to include them there. Therefore, option 1) needs a little more work up-front but you only need to do it once and then you can use all of those functions in all subsequent RNAseq based analysis packages.

You actually don't use any of Martin's function in your package at the moment that I can see so, really, you don't even need to have the `source("RNAseq_functs.R")` in the analysis file. Although, I am guessing that in future analysis you probably will use those functions so it would be good to already now incorporate the suggestions above.

**Comment by jasonserviss** [comment]
Read this after you have understood everything else: To complicate things a bit more... I set up the RNAseqFunctions package "in the rough" in order to let Martin, you, and others to modify it as needed. This especially concerns the documentation. At the moment there is very little documentation concerning examples, parameters (function arguments), and descriptions (function descriptions describing what the functions actually do). Part of the reason for this is I have no idea what many of the functions do or what the parameters are and was hoping Martin might fix the documentation so that the students could understand what the functions are doing and how to use them... Since I had an acute need to use some of the functions, in order for me to be able to reproduce Martin's data, I created my own package [sp.scRNAseqData](https://github.com/jasonserviss/sp.scRNAseqData) and included the functions that filter samples/genes and documented them. This can provide a good example of several things:

1) How to incorporate data into a package so that it is reproducible. This you can see in the inst/rawData directory where I have the raw .txt files and a corresponding script that processes them and saves the output in the data directory. 

2) How to document datasets. In addition, for each file in the data directory there is a corresponding file, with the same name in, the R directory. Here you can see the documentation for each dataset.

3) How to include functions that filter data into a package. In the R directory you can see the [filtering functions](https://github.com/jasonserviss/sp.scRNAseqData/blob/master/R/countFuns.R), and their documentation, that are used in the scripts in the inst/dataRaw directory.

**Comment by nathanaelandrews** [comment]
I don't have access to sp.scRNAseqData (404 not found). For now I'll just remove the Source() function. I initially needed it to use his plotting function so I can visualize the gene expression for multiple genes in the same figure, but that's not really necessary now.

**Comment by jasonserviss** [comment]
I added you as a collaborator to the sp.scRNAseqData package so you should have access now. Even if you resolved the issue, it could still be a useful resource for you to look at or for us to look at together. If you consider this issue resolved, you can close the issue.

**Comment by nathanaelandrews** [comment]
Yeah, I think this went a bit over my head. Not really sure how I would set up the R script so it is done properly, so I think we should sit down and go through this in person. For now, I've uploaded the updated Rmd-file (including my process from start to finish) and all the data I've generated with it.
