### ISSUE TITLE
script generating data (new classifications) in dataRaw

### ISSUE THREAD

**Issue by jasonserviss** [nathanaelandrews/sp.scRNAseqAnalysis#7]
It is not possible to tell by looking at Cluster_By_Cell_Type.Rmd exactly what you saved in the newclass.csv file. Formally, the script that generates newclass.csv should be in inst/rawData and then save the output from the script in the data folder (see #4). Then you can use the Cluster_By_Cell_Type.Rmd to do the actual **analysis**, i.e. visualise the new classifications, explain how/why they were produced, run the spSwarm method, show the results from the swarm deconvolution, etc.

**Comment by nathanaelandrews** [comment]
So this means I should have two .Rmd files? One for generating the new classifications and one with the functions for visualization/analysis? Does the same go for creating the spSwam object?

**Comment by jasonserviss** [comment]
Some definitions first:

1) .Rmd file = R markdown file. These are dynamic files that include mixed types of input, R code, text, images, etc. They can be rendered, or "knitted", and, in the end, end up being .html or .md files. The .Rmd file in itself is not very useful, it is the rendered version (i.e. the .html or .md file) that is useful.

2) .R file = R script file. These include R script and can be loaded into an active session (with: source("myRscript.R") or called from the command line (with: Rscript myRscript.R). These do not necessarily output any file and are not rendered to another file type. When you run the file the code contained in it is either executed in the active session or executed in the background (depending on where you "call" the file). So for example, you could have an .R file with the following inside:

`print("I am an R script file")`

If you name this file "myRscript.R" and then on the command line run `Rscript myRscript.R` it will 1) start R 2) run the code in the myRscript.R file (which in this case will print "I am an R script file" to the screen), 3) exit R. (I am not 100% sure this works the same way in Windows but I would assume it does).

To answer your question: typically scripts that generate data, that will be saved in the data folder, live in the inst/rawData folder. These scripts are not .Rmd but instead simple .R files. So in your case, you would probably want to do everything that you need to do to generate the new classifications in a .R file (including saving the new classifications to the data folder). Then, in a .Rmd file, I would 1) run the spCounts method and plots (if so desired) (here you will also need the counts data to live in the data folder, and thus, the same setup as other files living in the data folder, i.e. as I described above), then 2) load the new classifications from the data folder into the Rmd session (since you will have the classifications in your package's data folder, the classifications will be loaded automatically when you have `library(sp.scRNAseqAnalysis)` in the .Rmd code), 3) put the new classifications into the spUnsupervised object, 4) make the spUnsupervised plots, 5) run the spSwarm method, and 6) plot the results. 

I realise as I am writing this that it potentially is a bit complicated.... If you need help, let me know and I can walk you through it in person.

**Comment by jasonserviss** [comment]
discussed in person
